### ISSUE TITLE
Cant seem to change ore list after first use

### ISSUE THREAD

**Issue by Shortyuk** [sergey-koumirov/AesPublica#1]
Hi
I cant seem to be able to change anything in the ore list or recalculate after first use.
I change items in the ore list then go back to the main screen click on the cog icon but it gives me no options. I have tried using a different browser and logging in again however my information is retained and I end up with the same ore calculations no matter what blueprint I try ?
![orecalc](https://user-images.githubusercontent.com/34841767/34454677-27c79dc0-ed68-11e7-9798-5c8be0a11c4f.JPG)

**Comment by sergey-koumirov** [comment]
Have you saved changes?
(click on blue icon above "Hi-Sec Ores" text)

**Comment by sergey-koumirov** [comment]
There was (and maybe still is) bug with multiple prices. I think it broke your calculation.
Looks like I fixed it.

**Comment by Shortyuk** [comment]
That's great thanks :-)
